version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8

    working_directory: /tmp/eth-block-timestamp

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build library
          command: npm run build
      - save_cache:
          paths:
            - dist
          key: dist-{{ .Branch }}-{{ .Revision }}

workflows:
  version: 2
  test:
    jobs:
      - test
